/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminSessionsRouteImport } from './routes/admin.sessions'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as ApiConsultationRouteImport } from './routes/api/consultation'
import { Route as CounsellorDashboardRouteImport } from './routes/counsellor.dashboard'
import { Route as CounsellorLoginRouteImport } from './routes/counsellor.login'
import { Route as CounsellorSessionsRouteImport } from './routes/counsellor.sessions'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsSlugRouteImport } from './routes/destinations.$slug'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesSlugRouteImport } from './routes/resources.$slug'
import { Route as UniversitiesIndexRouteImport } from './routes/universities.index'
import { Route as UniversitiesSlugRouteImport } from './routes/universities.$slug'
import { Route as AdminCounsellorsIndexRouteImport } from './routes/admin.counsellors.index'
import { Route as AdminCounsellorsIdRouteImport } from './routes/admin.counsellors.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConsultationRoute = ApiConsultationRouteImport.update({
  id: '/api/consultation',
  path: '/api/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorDashboardRoute = CounsellorDashboardRouteImport.update({
  id: '/counsellor/dashboard',
  path: '/counsellor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorLoginRoute = CounsellorLoginRouteImport.update({
  id: '/counsellor/login',
  path: '/counsellor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CounsellorSessionsRoute = CounsellorSessionsRouteImport.update({
  id: '/counsellor/sessions',
  path: '/counsellor/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsSlugRoute = DestinationsSlugRouteImport.update({
  id: '/destinations/$slug',
  path: '/destinations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesSlugRoute = ResourcesSlugRouteImport.update({
  id: '/resources/$slug',
  path: '/resources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesIndexRoute = UniversitiesIndexRouteImport.update({
  id: '/universities/',
  path: '/universities/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversitiesSlugRoute = UniversitiesSlugRouteImport.update({
  id: '/universities/$slug',
  path: '/universities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCounsellorsIndexRoute = AdminCounsellorsIndexRouteImport.update({
  id: '/admin/counsellors/',
  path: '/admin/counsellors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCounsellorsIdRoute = AdminCounsellorsIdRouteImport.update({
  id: '/admin/counsellors/$id',
  path: '/admin/counsellors/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/consultation': typeof ApiConsultationRoute
  '/counsellor/dashboard': typeof CounsellorDashboardRoute
  '/counsellor/login': typeof CounsellorLoginRoute
  '/counsellor/sessions': typeof CounsellorSessionsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/admin/counsellors/$id': typeof AdminCounsellorsIdRoute
  '/admin/counsellors/': typeof AdminCounsellorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/consultation': typeof ApiConsultationRoute
  '/counsellor/dashboard': typeof CounsellorDashboardRoute
  '/counsellor/login': typeof CounsellorLoginRoute
  '/counsellor/sessions': typeof CounsellorSessionsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/destinations': typeof DestinationsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/universities': typeof UniversitiesIndexRoute
  '/admin/counsellors/$id': typeof AdminCounsellorsIdRoute
  '/admin/counsellors': typeof AdminCounsellorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services': typeof ServicesRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/api/consultation': typeof ApiConsultationRoute
  '/counsellor/dashboard': typeof CounsellorDashboardRoute
  '/counsellor/login': typeof CounsellorLoginRoute
  '/counsellor/sessions': typeof CounsellorSessionsRoute
  '/destinations/$slug': typeof DestinationsSlugRoute
  '/resources/$slug': typeof ResourcesSlugRoute
  '/universities/$slug': typeof UniversitiesSlugRoute
  '/destinations/': typeof DestinationsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/universities/': typeof UniversitiesIndexRoute
  '/admin/counsellors/$id': typeof AdminCounsellorsIdRoute
  '/admin/counsellors/': typeof AdminCounsellorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/services'
    | '/success-stories'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/sessions'
    | '/admin/students'
    | '/api/consultation'
    | '/counsellor/dashboard'
    | '/counsellor/login'
    | '/counsellor/sessions'
    | '/destinations/$slug'
    | '/resources/$slug'
    | '/universities/$slug'
    | '/destinations/'
    | '/resources/'
    | '/universities/'
    | '/admin/counsellors/$id'
    | '/admin/counsellors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/services'
    | '/success-stories'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/sessions'
    | '/admin/students'
    | '/api/consultation'
    | '/counsellor/dashboard'
    | '/counsellor/login'
    | '/counsellor/sessions'
    | '/destinations/$slug'
    | '/resources/$slug'
    | '/universities/$slug'
    | '/destinations'
    | '/resources'
    | '/universities'
    | '/admin/counsellors/$id'
    | '/admin/counsellors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/services'
    | '/success-stories'
    | '/terms'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/sessions'
    | '/admin/students'
    | '/api/consultation'
    | '/counsellor/dashboard'
    | '/counsellor/login'
    | '/counsellor/sessions'
    | '/destinations/$slug'
    | '/resources/$slug'
    | '/universities/$slug'
    | '/destinations/'
    | '/resources/'
    | '/universities/'
    | '/admin/counsellors/$id'
    | '/admin/counsellors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesRoute: typeof ServicesRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  ApiConsultationRoute: typeof ApiConsultationRoute
  CounsellorDashboardRoute: typeof CounsellorDashboardRoute
  CounsellorLoginRoute: typeof CounsellorLoginRoute
  CounsellorSessionsRoute: typeof CounsellorSessionsRoute
  DestinationsSlugRoute: typeof DestinationsSlugRoute
  ResourcesSlugRoute: typeof ResourcesSlugRoute
  UniversitiesSlugRoute: typeof UniversitiesSlugRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
  UniversitiesIndexRoute: typeof UniversitiesIndexRoute
  AdminCounsellorsIdRoute: typeof AdminCounsellorsIdRoute
  AdminCounsellorsIndexRoute: typeof AdminCounsellorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/consultation': {
      id: '/api/consultation'
      path: '/api/consultation'
      fullPath: '/api/consultation'
      preLoaderRoute: typeof ApiConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor/dashboard': {
      id: '/counsellor/dashboard'
      path: '/counsellor/dashboard'
      fullPath: '/counsellor/dashboard'
      preLoaderRoute: typeof CounsellorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor/login': {
      id: '/counsellor/login'
      path: '/counsellor/login'
      fullPath: '/counsellor/login'
      preLoaderRoute: typeof CounsellorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counsellor/sessions': {
      id: '/counsellor/sessions'
      path: '/counsellor/sessions'
      fullPath: '/counsellor/sessions'
      preLoaderRoute: typeof CounsellorSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$slug': {
      id: '/destinations/$slug'
      path: '/destinations/$slug'
      fullPath: '/destinations/$slug'
      preLoaderRoute: typeof DestinationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$slug': {
      id: '/resources/$slug'
      path: '/resources/$slug'
      fullPath: '/resources/$slug'
      preLoaderRoute: typeof ResourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/': {
      id: '/universities/'
      path: '/universities'
      fullPath: '/universities/'
      preLoaderRoute: typeof UniversitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universities/$slug': {
      id: '/universities/$slug'
      path: '/universities/$slug'
      fullPath: '/universities/$slug'
      preLoaderRoute: typeof UniversitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/counsellors/': {
      id: '/admin/counsellors/'
      path: '/admin/counsellors'
      fullPath: '/admin/counsellors/'
      preLoaderRoute: typeof AdminCounsellorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/counsellors/$id': {
      id: '/admin/counsellors/$id'
      path: '/admin/counsellors/$id'
      fullPath: '/admin/counsellors/$id'
      preLoaderRoute: typeof AdminCounsellorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesRoute: ServicesRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  ApiConsultationRoute: ApiConsultationRoute,
  CounsellorDashboardRoute: CounsellorDashboardRoute,
  CounsellorLoginRoute: CounsellorLoginRoute,
  CounsellorSessionsRoute: CounsellorSessionsRoute,
  DestinationsSlugRoute: DestinationsSlugRoute,
  ResourcesSlugRoute: ResourcesSlugRoute,
  UniversitiesSlugRoute: UniversitiesSlugRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
  UniversitiesIndexRoute: UniversitiesIndexRoute,
  AdminCounsellorsIdRoute: AdminCounsellorsIdRoute,
  AdminCounsellorsIndexRoute: AdminCounsellorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
