// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { supabase } from './client'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    let { data } = await supabase.auth.getSession()
    let session = data.session

    // If session exists and the access token is already expired or expiring within 30 seconds,
    // refresh it once to ensure the server receives a valid token.
    if (session?.expires_at && session.expires_at * 1000 - Date.now() < 30_000) {
      try {
        const { data: refreshed, error: refreshError } = await supabase.auth.refreshSession()
        if (!refreshError && refreshed?.session) {
          session = refreshed.session
        }
      } catch (err) {
        console.warn('[AUTH_ATTACHER] Failed to refresh expiring session:', err)
      }
    }

    const token = session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
