// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dogbbwtlfdwsjijjxsru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvZ2Jid3RsZmR3c2ppamp4c3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4NzU4NDgsImV4cCI6MjEwNDQ1MTg0OH0.3lJRU5l2lA4aPyJCCpKTfINmCmkchc5Ig_2Shtqe1f0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});